### ISSUE TITLE
Problem install on Mac OS X

### ISSUE THREAD

**Issue by sotoz** [anselal/docker-isthmos#3]
Hello, 

I'm trying to install isthmos to my machine locally (MBP with mac os 10.11.6). 
I get the following output:
 
```
$ sudo -H pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname==3.5.0.1 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): click==6.6 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Collecting docker-py==1.8.1 (from -r requirements.txt (line 3))
  Downloading docker_py-1.8.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.1MB/s
Collecting Flask==0.11.1 (from -r requirements.txt (line 4))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB)
    100% |████████████████████████████████| 81kB 2.2MB/s
Collecting ipaddress==1.0.16 (from -r requirements.txt (line 5))
  Downloading ipaddress-1.0.16-py27-none-any.whl
Collecting itsdangerous==0.24 (from -r requirements.txt (line 6))
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 8.0MB/s
Collecting Jinja2==2.8 (from -r requirements.txt (line 7))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 3.0MB/s
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 8))
  Downloading MarkupSafe-0.23.tar.gz
Requirement already satisfied (use --upgrade to upgrade): requests==2.10.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 9))
Collecting six==1.10.0 (from -r requirements.txt (line 10))
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting websocket-client==0.37.0 (from -r requirements.txt (line 11))
  Downloading websocket_client-0.37.0.tar.gz (194kB)
    100% |████████████████████████████████| 194kB 4.5MB/s
Collecting Werkzeug==0.11.10 (from -r requirements.txt (line 12))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB)
    100% |████████████████████████████████| 307kB 2.5MB/s
Installing collected packages: six, websocket-client, ipaddress, docker-py, itsdangerous, Werkzeug, MarkupSafe, Jinja2, Flask
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-0loQwi-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
```

I can think of the installation being incompatible with Mac OS X. Is this the case, or the package `six` is problematic??

**Comment by anselal** [comment]
I personally have not tested it on OS X but it should work. Check out this issue https://github.com/pypa/pip/issues/3165
Can you try to install it on a newly virtual env or try something like `sudo -H pip install -r requirements.txt --upgrade --ignore-installed six`

**Comment by sotoz** [comment]
Yeap,

I run `sudo -H pip install -r requirements.txt --upgrade --ignore-installed` and that did the trick. For some reason pip couldn't uninstall/reinstall `six`. 

I'll do some more debugging and I'll try to provide some helpful feedback :)
